services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  initdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test
      - PGPASSWORD=test
    command: >
      sh -c "
        psql -h db -U test postgres -c 'CREATE DATABASE account;' || true;
        psql -h db -U test account -c 'SELECT 1;' && exit 0 || exit 1
      "
    depends_on:
      - db
    restart: on-failure