services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/account
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/account
      - SPRING_FLYWAY_USER=test
      - SPRING_FLYWAY_PASSWORD=test
    depends_on:
      - db
      - initdb
    restart: on-failure
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  initdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test
      - PGPASSWORD=test
    command: >
      sh -c "
        psql -h db -U test postgres -c 'CREATE DATABASE account;' || true;
        psql -h db -U test account -c 'SELECT 1;'
      "
    depends_on:
      - db
    restart: on-failure